[package]
name = "juno-receipt-host"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
juno-receipt-methods = { path = "../methods" }
risc0-zkvm = { version = "3.0.4", default-features = false, features = ["prove"] }

[dev-dependencies]
sha2 = "0.10.8"

