[package]
name = "juno-receipt-logic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sha2 = "0.10.8"
orchard = { version = "0.12.0", default-features = false, features = ["std"] }

