[package]
name = "juno-attestation-methods"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
risc0-build = "3.0.4"

[dependencies]

[package.metadata.risc0]
methods = ["guest"]

